language: node_js
node_js:
  - 4.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm

env:
  - CC=gcc-4.8 CXX=g++-4.8

before_script:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
  export DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start;
  fi

script:
- npm run lint
- npm test
